Ensure correct attack damage on slot change
hpfxd/PandaSpigot pull request #153
Opened 2023-07-12 02:38 UTC by ThatApplePieGuy

fixes a vanilla bug where attack damage isnt updated in time if you attack too fast after changing slots. demo: https://youtu.be/QyarG6DSh1c

2023-07-12 03:24 UTC, hpfxd approved these changes

2023-07-14 16:11 UTC, uRyanxD approved these changes
LGTM, however, I don't have time to test the patch

2023-07-14 17:44 UTC, MachineBreaker requested changes

2023-07-14 17:44 UTC, MachineBreaker commented on patches/server/0098-Ensure-correct-attack-damage-on-slot-change.patch
> ++                if (this.inventory.items[this.inventory.prevItemInHandIndex] != null) {
Make this a single array access

2023-07-14 17:46 UTC, andreasdc commented
Better change this in held item packet

2023-07-15 14:03 UTC, MachineBreaker approved these changes

2023-07-18 16:55 UTC, bl4stySKID commented
this breaks what is known as "rod tricking" which is a pretty used mechanic on 1.8 for anyone wondering

2023-09-06 00:45 UTC, iamnoksio commented
[00:41:06] [Server thread/WARN]: Failed to handle packet for /199.102.202.174:59257
java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
	at net.minecraft.server.v1_7_R4.AttributeModifiable.a(SourceFile:74) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:847) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInHeldItemSlot.a(SourceFile:30) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInHeldItemSlot.handle(SourceFile:8) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:197) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:73) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:799) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:319) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:652) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:566) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) ~[spigot.jar:git-PaperSpigot-1f7d532]

2023-09-06 00:45 UTC, iamnoksio commented
[00:41:06] [Server thread/WARN]: Failed to handle packet for /
java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
	at net.minecraft.server.v1_7_R4.AttributeModifiable.a(SourceFile:74) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:847) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInHeldItemSlot.a(SourceFile:30) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInHeldItemSlot.handle(SourceFile:8) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:197) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:73) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:799) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:319) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:652) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:566) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) ~[spigot.jar:git-PaperSpigot-1f7d532]

2023-09-09 01:38 UTC, ThatApplePieGuy commented
can you reproduce this in 1.8?

2024-03-07 23:00 UTC, closed without merging